datacarpentry/r-intro-geospatial

- _episodes_rmd/04-data-structures-part1.Rmd
- _episodes_rmd/05-data-structures-part2.Rmd
Following up our discussion about issue #10 I removed the usage of feline dataset.
> Synthesize Exploring Data frames

- _episodes_rmd/04-data-structures-part1.Rmd
Added missing space in nordic_orig as suggested by @ErinBecker
> add a space after the comma in nordic_orig

- _episodes/07-control-flow.md
right now the solution isn't hidden and challenge is not displayed correctly due to the ``` at the end of the challenge.
> Display challenge 4 correctly at lesson 7

- _episodes_rmd/01-rstudio-intro.Rmd
Makes cuts to "Introduction to R and RStudio" episode recommended in https://github.com/datacarpentry/r-intro-geospatial/issues/22. 
Since the "R Packages" section is removed here, we will need a short introduction to packages when the first package is used. This approach is used in the R Ecology lesson and helps to reduce cognitive load by only introducing concepts as they are needed by the learner.
> make cuts to 01-rstudio-intro

- _episodes_rmd/01-rstudio-intro.Rmd
Fixes https://github.com/datacarpentry/r-intro-geospatial/issues/44 and https://github.com/datacarpentry/r-intro-geospatial/issues/45
> update keyboard shortcut

- _episodes_rmd/04-data-structures-part2.Rmd
Fixes https://github.com/datacarpentry/r-intro-geospatial/issues/18
> removing columns and rows

- _episodes_rmd/02-project-intro.Rmd
Moved from raster vector lesson setup instructions
Fixes https://github.com/datacarpentry/r-raster-vector-geospatial/issues/237
> move directory setup instructions

- _episodes_rmd/04-data-structures-part2.Rmd
Same as https://github.com/datacarpentry/genomics-r-intro/pull/37 ;-)
> Canonicalize CRAN link

- _episodes_rmd/06-dplyr.Rmd
> Fixed broken link to dplyr vignette

- .gitignore
- Makefile
- _includes/lesson_footer.html
- _includes/navbar.html
- _layouts/base.html
- assets/css/lesson.scss
- assets/js/lesson.js
- bin/boilerplate/.travis.yml
- bin/boilerplate/_config.yml
- bin/lesson_check.py
- bin/repo_check.py
- bin/util.py
- bin/workshop_check.py
fix issue reported on Slack about code folding not working.
> Upgrade styles - fix solution folding

- _episodes_rmd/05-data-subsetting.Rmd
> Typo fix for 05-data-subsetting.Rmd

- .github/workflows/template.yml
- .github/workflows/website.yml
- Makefile
- assets/css/lesson.scss
- bin/boilerplate/CONTRIBUTING.md
- bin/dependencies.R
- bin/generate_md_episodes.R
- bin/install_r_deps.sh
- bin/lesson_check.py
- index.md
bring the latest version of the styles repository
> Upgrade styles

- _episodes_rmd/06-dplyr.Rmd
Alt-text submissions made by @tobyhodges during Core Team Accessibility session. Ready for review.
> adding alt-text to dplyr illustrations

- _episodes_rmd/02-project-intro.Rmd
Alt-text submission made by @tobyhodges during Core Team Accessibility session. Ready for review.
> add alt-text to screenshot showing bad folder layout

- _episodes_rmd/07-plot-ggplot2.Rmd
Alt-text submissions made by @ErinBecker during Core Team Accessibility session. Ready for review.
> adding alt-text for illustrations

- _episodes_rmd/04-data-structures-part2.Rmd
Think this chunk should be shown.  If the instructor skips the callout box, which downloads and loads the data from the web directly, they still need to load the data.  Think this box should be shown and then the instructor can decide if they want to use the callout box or not.
> show reading in data chunk

- _episodes_rmd/06-dplyr.Rmd
The Keypoints were amended to include the count() and n() as per the enumerated list.
<details>
<summary><strong>Instructions</strong></summary>
Thanks for contributing! :heart:
If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!
Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a …
> Update Key Points to match functions list

- episodes/01-rstudio-intro.Rmd
Added instructor note about intro to r and r studio
> added r studio instructor note

- episodes/01-rstudio-intro.Rmd
- episodes/02-project-intro.Rmd
- episodes/04-data-structures-part2.Rmd
- episodes/05-data-subsetting.Rmd
- episodes/06-dplyr.Rmd
- episodes/07-plot-ggplot2.Rmd
- episodes/08-writing-data.Rmd
- instructors/instructor-notes.md
Move the notes in `instructors/instructor-notes.md` to their corresponding episodes.
> Move instructor-notes to episodes.

- episodes/02-project-intro.Rmd
_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
Closes #123
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
This PR adds an instructor note, implementing a recommendation by the Curriculum Advisory Committee to close #123.
_If any relevant discussions have taken place elsewhere, please provide links to these._
None
<details>
For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).
Please keep in mind that lesson Maintainers are volunteers and it may be some time before they can respond …
> Add instructor note (Fixes #123)

- learners/setup.md
Adds a section anchor to the link for the workshop setup instructions
> Link to setup instructions

- README.md
_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
Closes #77 
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
The maintainers list (```README.md```) was updated to match the names stated at [data carpentry lessons](https://datacarpentry.org/lessons/#geospatial-curriculum).
> Maintainers list updated

- episodes/07-plot-ggplot2.Rmd
Add the change suggested by @mikemahoney218 to episode 7 regarding issue #142 raised by @LizZhou
Closes #142
> Closes #142

- README.md
Toby said I was supposed to put myself in the readme
> I forgot to add myself last year to the maintainer list
